defaults:
  - schema
  - _self_

base_model: gine
gine_model_bn: false
pe_method: spe
n_node_types: 28  
n_edge_types: 3
node_emb_dims: 128
pooling: add

phi_model_name: gin
pe_dims: 37  
n_phi_layers: 8
phi_hidden_dims: 40

#### DOESNT MATTER ####
psi_model_name: mlp
n_psis: 16
n_psi_layers: 3
psi_hidden_dims: 16
psi_activation: relu
num_heads: 4
pe_aggregate: add
#### DOESNT MATTER ####

n_base_layers: 4
base_hidden_dims: 128

n_mlp_layers: 3
mlp_hidden_dims: 128
mlp_use_bn: true
mlp_use_ln: false
mlp_activation: relu
mlp_dropout_prob: 0.0

residual: true
graph_norm: false  # ONLY USED FOR PNA BASE
batch_norm: true   # ONLY USED PHI GIN and PNA BASE

# data attributes
use_subset: true
train_batch_size: 128
val_batch_size: 128

BASIS: false # IF TRUE will run using basis vectors, otherwise will use random samples
num_samples: 120
RAND_k: 12
#mlp_nlayers: 0
#mlp_hid: 0
RAND_mlp_nlayers: 1
RAND_mlp_hid: 37  # shape that goes into PHI
RAND_mlp_out: 37
RAND_act: relu
RAND_LAP: None

# optimizer attributes
lr: 0.001
weight_decay: 0.000003
momentum: 0.9
nesterov: false

# scheduler attributes
n_warmup_steps: 100

# miscellaneous
n_epochs: 1400
out_dirpath: out/baseline
wandb: true
wandb_run_name: RPEARL
